version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: 
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Tests
          command: npm run test

      - deploy:
          name: Ubuntu server
          command: ssh root@appzcoder.com "cd ~/apps/nodejs-circle-ci; git pull; npm install; pm2 restart 2"
